First week.
Dev-incubator/WebAutoparkMaksim pull request #1
Opened 2021-12-06 16:39 UTC by creator-max

Add Entities. Create SQLTables. Create IRepository interface. Create Repositories for Entities.

2021-12-06 19:26 UTC, kuzmiich commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +        private const string _queryGetAll = "SELECT * FROM Details";
```suggestion
        private const string QueryGetAll = "SELECT * FROM Details";
```
Constant field is always written via Camel Case

2021-12-06 19:26 UTC, kuzmiich commented on WebAutopark/SQLScripts/CreateVehicles.sql
> +    [YearOfIssue]     SMALLINT                NOT NULL,
```suggestion
    [YearOfIssue]     INT                NOT NULL,
```
INT better

2021-12-06 19:26 UTC, kuzmiich commented on WebAutopark.DataAccesLayer/Repositories/BaseRepository.cs
> +            using(DbConnection db = new SqlConnection(ConnectionString))
Move DbConnection initialization to constructor

2021-12-06 22:40 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +        private const string _queryGetAll = "SELECT * FROM Details";
Yeah, my mistake. But... Camel Case or Pascal Case? I read that Pascal Case is recommended for constants.

2021-12-06 22:49 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/BaseRepository.cs
> +            using(DbConnection db = new SqlConnection(ConnectionString))
Okay, i'll change it

2021-12-08 17:34 UTC, kuzmiich commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +        public virtual async Task<Detail> GetByIdAsync(int id) => await Connection.QueryFirstOrDefaultAsync<VehiclieType>(QueryGetByID, id);
```suggestion
        public virtual async Task<Detail> GetByIdAsync(int id) => await Connection.QueryFirstOrDefaultAsync<Detail>(QueryGetByID, id);
```

2021-12-08 17:34 UTC, kuzmiich commented on WebAutopark.DataAccesLayer/Repositories/BaseRepository.cs
> +    public abstract class BaseRepository<T> : IDisposable, IAsyncDisposable
Rename this class. 
This class provide connection initialization and Dispose this connection

2021-12-08 17:45 UTC, kuzmiich commented on WebAutopark.DataAccesLayer/Repositories/BaseRepository.cs
> +    public abstract class BaseRepository<T> : IDisposable, IAsyncDisposable
U want generic type for this class?

2021-12-08 18:14 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +        public virtual async Task<Detail> GetByIdAsync(int id) => await Connection.QueryFirstOrDefaultAsync<VehiclieType>(QueryGetByID, id);
Thx, fixed :з

2021-12-08 18:25 UTC, kuzmiich approved these changes

2021-12-09 21:11 UTC, PushMeNow commented on WebAutopark.DataAccesLayer/Entities/Vehicle.cs
> +            : 0;
Entities mustn't have calculation and any business logic.

2021-12-09 21:23 UTC, PushMeNow commented on WebAutopark.DataAccesLayer/Entities/Vehicle.cs
> +        public double MileageKm { get; set; }
We can add dimension in the name of field when it could store unusual data but currently we are not expect data like this.

2021-12-09 21:24 UTC, PushMeNow commented on WebAutopark.DataAccesLayer/Interfaces/IRepository.cs
> +        Task DeleteAsync(int id);
We don't use Async ends in methods when there are no sync methods.

2021-12-09 21:26 UTC, PushMeNow commented on WebAutopark.DataAccesLayer/Repositories/ConnectionProvider.cs
> +        public ConnectionProvider(string connectionString)
Create ConnectionStringProvider class. Don't inject this string directly.

2021-12-09 21:30 UTC, PushMeNow commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +                                           "DetailName = @DetailName," +
Redundant comma after parameter.

2021-12-09 21:33 UTC, PushMeNow commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +        private const string QueryCreate = "INSERT Details VALUES(DetailName)";
<code>insert <b>INTO</b> Details<b>(DetailName)</b> values<b>(@DetailName)</b></code>

2021-12-09 21:33 UTC, PushMeNow commented on WebAutopark.DataAccesLayer/Repositories/VehicleRepository.cs
> +        private const string QueryCreate = "INSERT Vehicles VALUES(" +
insert into {tablename}(...fieldnames) ....
[https://www.w3schools.com/sql/sql_insert.asp](https://www.w3schools.com/sql/sql_insert.asp)

make these change everywhere in insert statements

2021-12-09 21:38 UTC, PushMeNow commented on WebAutopark/SQLScripts/CreateOrderElements.sql
> +CREATE TABLE [OrdersElements]
*OrderElement (without 's' at the end of Order)

2021-12-11 11:41 UTC, creator-max commented on WebAutopark.DataAccesLayer/Interfaces/IRepository.cs
> +        Task DeleteAsync(int id);
Thanks, i'll know

2021-12-11 11:42 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +                                           "DetailName = @DetailName," +
Yeah, my mistake 👍

2021-12-11 11:43 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/VehicleRepository.cs
> +        private const string QueryCreate = "INSERT Vehicles VALUES(" +
Changed

2021-12-11 11:43 UTC, creator-max commented on WebAutopark/SQLScripts/CreateOrderElements.sql
> +CREATE TABLE [OrdersElements]
Renamed

2021-12-11 11:46 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/ConnectionProvider.cs
> +        public ConnectionProvider(string connectionString)
I created that, thanks for the advice.

2021-12-11 19:08 UTC, im-kborovik requested changes

2021-12-11 19:08 UTC, im-kborovik commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +        private const string QueryCreate = "INSERT INTO Details VALUES(@DetailName)";
Will be broken on first run becasue you did wrote changing columns

2021-12-11 19:08 UTC, im-kborovik commented on WebAutopark/Startup.cs
> +        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, DetailRepository detailRepository)
wait why do you need repo here injection?

2021-12-11 19:08 UTC, im-kborovik commented on WebAutopark/Startup.cs
> +            services.AddSingleton<IConnectionStringProvider, MsSQLStringProvider>(_ => new MsSQLStringProvider(Configuration));
Remove provider. It is included in DI be default.

2021-12-11 19:08 UTC, im-kborovik commented on WebAutopark/Startup.cs
> +            services.AddTransient<VehicleTypeRepository>();
Scoped. and where are interfaces for these repos?

2021-12-11 20:10 UTC, creator-max commented on WebAutopark/Startup.cs
> +        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, DetailRepository detailRepository)
oops. I'll delete it

2021-12-11 23:52 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/DetailRepository.cs
> +        private const string QueryCreate = "INSERT INTO Details VALUES(@DetailName)";
No, it's okay, because first column is IDENTITY and it increments automatically. I have checked this query.

2021-12-11 23:52 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/Connection/MsSQLStringProvider.cs
> +    public class MsSQLStringProvider : IConnectionStringProvider
Renamed

2021-12-11 23:52 UTC, creator-max commented on WebAutopark/Startup.cs
> +            services.AddSingleton<IConnectionStringProvider, MsSQLStringProvider>(_ => new MsSQLStringProvider(Configuration));
Yeah, deleted

2021-12-11 23:55 UTC, creator-max commented on WebAutopark/Startup.cs
> +            services.AddTransient<VehicleTypeRepository>();
Okay, i added that

2021-12-13 20:55 UTC, PushMeNow approved these changes

2021-12-14 19:18 UTC, merged