Third week.
Dev-incubator/WebAutoparkMaksim pull request #3
Opened 2021-12-22 18:19 UTC by creator-max

Add controllers and views. Update Vehicle entity, VehicleRepository, Vehicle table in msSql.

2021-12-22 18:55 UTC, PushMeNow requested changes

2021-12-22 18:55 UTC, PushMeNow commented on WebAutopark/Controllers/DetailController.cs
> +        public ActionResult Create()
Group it together with another Create action

2021-12-22 18:55 UTC, PushMeNow commented on WebAutopark/Controllers/DetailController.cs
> +        public async Task<IActionResult> Edit(Detail detail)
Use model classes instead of entity classes

2021-12-22 18:55 UTC, PushMeNow commented on WebAutopark/Controllers/HomeController.cs
>          }
HomeController has to have only common information about application. You already have VehicleController for getting of vehicle information.

2021-12-22 18:55 UTC, PushMeNow commented on WebAutopark/Controllers/VehicleController.cs
> +        public static List<VehicleType> VehicleTypes;
Bad approach. Controller mustn't have any static information. Also I really don't see the reason of this field because static fields are sharing between all clients of application. If you need to transfer additional data on View layer you can use ViewBag object. This is his main responsibility.

2021-12-22 18:55 UTC, PushMeNow commented on WebAutopark/Views/Detail/Create.cshtml
> +            <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
English

2021-12-22 18:55 UTC, PushMeNow commented on WebAutopark/Views/VehicleType/Delete.cshtml
> +            @Model.TypeId
TypeId != Name

2021-12-23 18:30 UTC, PushMeNow requested changes

2021-12-23 18:30 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/DataTransferObjects/VehicleDto.cs
> +        public VehicleTypeDto VehicleType { get; set; }
Useless field in dto. You already have VehicleTypeId to join with Vehicle type

2021-12-23 18:30 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Services/Base/BaseService.cs
> +        public virtual async Task Create(TDto item)
Remove 'virtual' keyword where you don't use override

2021-12-23 18:30 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Services/Base/BaseService.cs
> +            await _repository.Create(_mapper.Map<TEntity>(item));
Don't inline pls. Create local variable. Also I don't see the reason to await it.

2021-12-23 18:30 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Services/Base/BaseService.cs
> +            var entities =  await (_repository.GetAll());
Brackets?

2021-12-23 18:30 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Interfaces/IBusinessDto.cs
> +    public interface IBusinessDto
Actually I don't understand why do you need this interface.

2021-12-23 18:30 UTC, PushMeNow commented on WebAutopark/Controllers/VehicleController.cs
> +                vehicles = vehicles.Where(v => v.Model.ToUpper().Contains(name));
Why do you need this action which converting of names?

2021-12-23 18:30 UTC, PushMeNow commented on WebAutopark/Controllers/VehicleController.cs
> +                _mapper.Map<VehicleDto>(vehicleViewModel));
I see nowhere check modal on validation.

2021-12-23 18:37 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/Services/Base/BaseService.cs
> +        public virtual async Task Create(TDto item)
Removed

2021-12-23 18:38 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/Interfaces/IBusinessDto.cs
> +    public interface IBusinessDto
Removed

2021-12-23 19:02 UTC, creator-max commented on WebAutopark/Controllers/VehicleController.cs
> +                vehicles = vehicles.Where(v => v.Model.ToUpper().Contains(name));
To get a case-insensitive search result ... But i replaced it with `str1.Equals(str2, StringComparison.OrdinalIgnoreCase)`

2021-12-23 19:03 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/Services/Base/BaseService.cs
> +            await _repository.Create(_mapper.Map<TEntity>(item));
Sorry, i'll fix it

2021-12-23 19:37 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/DataTransferObjects/VehicleDto.cs
> +        public VehicleTypeDto VehicleType { get; set; }
Removed

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +        {
Question: Why not `[HttpGet]`? Since `[HttpPost]` mostly used for transfer data to the server it's looks here very strange. If you wanted to avoid collistion of two methods named `Index` you could do the following:
1. Add string param to original method and just check it for null.
2. Create a new method and separate them by a different names or routes (with the help of attributes)

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +        {
Suggestion: Add `[HttpGet]`

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +        }
Suggestion: nameof(Index). Find the same places in other controllers
```suggestion
            }
            return RedirectToAction(nameof(Index));
        }
```

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +        {
Already mentioned above

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +        {
Suggestion: Add [HttpGet]

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +        public async Task<IActionResult> Create()
Suggestion: remove this comments or introduce XML-comments

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        }
Remark: all the comment above for controllers are also appliciable here

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/MapperProfiles/ViewModelDtoProfile.cs
> +
Nitpick (non-blocking): remove space

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleViewModel.cs
> +
Nitpick (non-blocking): remove space.

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleViewModel.cs
> +        public string LicensePlat { get; set; }
Suggestion: `LicensePlate`

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleViewModel.cs
> +        public int YearOfIssue { get; set; }
Will lead to a new Jira issue with description "change validation rules in 2023" 😄

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleViewModel.cs
> +        public int YearOfIssue { get; set; }
And also why start in 1950. Don't you consider to sell retro cars?

2021-12-26 01:13 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleTypeViewModel.cs
> +        [Range(0.5, 3, ErrorMessage="Tax Coefficient must be from 0.5 to 3.0")]
Nitpick (non-blocking): spaces

2021-12-26 13:33 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/DataTransferObjects/DetailDto.cs
> +        public string DetailName { get; set; }
Renamed

2021-12-26 18:03 UTC, PushMeNow approved these changes

2021-12-26 18:03 UTC, PushMeNow commented on WebAutopark/Models/VehicleViewModel.cs
> +        public int YearOfIssue { get; set; }
@ArtyomKolosov2 omg. thank I didn't see this validation on first review. I would suggest to remove this validation because I haven't written about exact manufactured date for vehicles. @creator-max if you want to add validation here you can add `>=1` for now. Yeah I know it will looks like pretty strange but it will be enough.

2021-12-26 18:03 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Services/Base/BaseService.cs
> +        }
I don't like arrow functions. @ArtyomKolosov2 don't impose bad practice :)

2021-12-26 19:06 UTC, ArtyomKolosov2 commented on WebAutopark.BusinessLogicLayer/Services/Base/BaseService.cs
> +        }
I guess that's just a matter of taste 😄 I love them very much

2021-12-26 19:08 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/DetailController.cs
> +        public async Task<IActionResult> Edit(DetailViewModel detailViewModel)
I mean, it is named "Edit" and I expected `[HttpPut`] or `[HttpPatch]`

2021-12-27 19:38 UTC, creator-max commented on WebAutopark/Controllers/VehicleController.cs
> +        {
Thanks, I will.

2021-12-27 23:18 UTC, ArtyomKolosov2 approved these changes

2021-12-28 14:48 UTC, merged