Fourth week
Dev-incubator/WebAutoparkMaksim pull request #4
Opened 2022-01-06 08:06 UTC by creator-max

Added services, controllers, views for Order and OrderElement. Added sorting, calculating tax per month, calculating max km for VehicleViewModel.

2022-01-06 18:54 UTC, PushMeNow requested changes

2022-01-06 18:54 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/DataTransferObjects/OrderDTO.cs
> +    public class OrderDTO
`Dto` Don't use caps pls

2022-01-06 18:54 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Interfaces/IOrderElementService.cs
> +    public interface IOrderElementService : IDtoService<OrderElementDTO>
Rename pls DtoService -> DataService. I don't like DtoService name because it says me nothing.

2022-01-06 18:54 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Services/OrderElementService.cs
> +            order.Detail = detail;
You have to make this on data layer. Make these changes everywhere where you try to map nested navigation properties.

2022-01-06 18:54 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Services/VehicleService.cs
> +            return vehicles.SortVehiclesBy(sortOrder);
You have to sort data in data layer by sql.

2022-01-06 18:54 UTC, PushMeNow commented on WebAutopark/Controllers/OrderController.cs
> +        }
Well I don't see sense in this page. It is responsibility of OrderItemController. So I would suggest redirecting user there after order creation.

2022-01-06 18:54 UTC, PushMeNow commented on WebAutopark/Controllers/OrderElementController.cs
> +        public async Task<IActionResult> Create(OrderElementViewModel orderElementView)
I would create checkbox 'CreateAnother' in view model. If is true user will redirect on 'Create' endpoint again to create still one item.

2022-01-06 23:54 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/DataTransferObjects/OrderDTO.cs
> +    public class OrderDTO
Renamed

2022-01-06 23:55 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/Interfaces/IOrderElementService.cs
> +    public interface IOrderElementService : IDtoService<OrderElementDTO>
Renamed

2022-01-07 01:15 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/Services/OrderElementService.cs
> +            order.Detail = detail;
Moved to DLL

2022-01-07 01:15 UTC, creator-max commented on WebAutopark.BusinessLogicLayer/Services/VehicleService.cs
> +            return vehicles.SortVehiclesBy(sortOrder);
Moved to DLL

2022-01-07 13:26 UTC, creator-max commented on WebAutopark/Controllers/OrderElementController.cs
> +        public async Task<IActionResult> Create(OrderElementViewModel orderElementView)
Created

2022-01-07 13:34 UTC, creator-max commented on WebAutopark/Controllers/OrderController.cs
> +        }
Moved information page to OrderElementController. But i don't see reason in redirecting there after creation. User can see all OrerElements during order cretaion in OrderController.ChangeOrderElements )

2022-01-09 15:18 UTC, PushMeNow requested changes

2022-01-09 15:18 UTC, PushMeNow commented on WebAutopark.BusinessLogicLayer/Services/VehicleService.cs
> +            var sortOrder = _mapper.Map<SortOrder>(sortOrderDto);
SortOrderDto is redundant because it is not part of Database. So you can use SortOrder only.

2022-01-09 15:18 UTC, PushMeNow commented on WebAutopark/Controllers/OrderController.cs
> +        }
Remove it and use Create method in OrderElementController.

2022-01-09 15:18 UTC, PushMeNow commented on WebAutopark/Startup.cs
>                                     typeof(ViewModelDTOProfile));
AddAutomapper can scan whole Assembly. You have to pass it as parameter.

2022-01-10 14:28 UTC, kuzmiich requested changes

2022-01-10 14:28 UTC, kuzmiich commented on WebAutopark.DataAccesLayer/Repositories/VehicleRepository.cs
> +                                           "ON [V].[VehicleTypeId] = [VT].[TypeId] ";
```suggestion
                                           "ON [V].[VehicleTypeId] = [VT].[TypeId]";
```

2022-01-10 14:28 UTC, kuzmiich commented on WebAutopark/Controllers/OrderElementController.cs
> +            ViewBag.Details = detailsView;
Create additional method for it like SetupDetails()

2022-01-10 14:55 UTC, creator-max commented on WebAutopark.DataAccesLayer/Entities/Order.cs
> +        public DateTime Date { get; set; }
I need also to get Date from DB.

2022-01-10 14:56 UTC, creator-max commented on WebAutopark.DataAccesLayer/Repositories/OrderRepository.cs
> +                                                    "        Inserted.Date " +
Okay, i'll fix it

2022-01-10 19:43 UTC, PushMeNow requested changes

2022-01-10 19:43 UTC, PushMeNow commented on WebAutopark/Controllers/OrderElementController.cs
> +    }
Where are Update and Delete methods?

2022-01-10 19:43 UTC, PushMeNow commented on WebAutopark/Controllers/OrderController.cs
> +    }
Where are Update and Delete methods?

2022-01-14 18:22 UTC, creator-max commented on WebAutopark/Controllers/OrderController.cs
> +    }
Added

2022-01-14 18:25 UTC, creator-max commented on WebAutopark/Controllers/OrderElementController.cs
> +    }
Added Delete method. But i have no idea, which info i can change in Order entity... There are only OrderId and VehicleId fields

2022-01-14 18:25 UTC, creator-max commented on WebAutopark/Models/OrderViewModel.cs
> +        public DateTime Date { get; set; }
removed.

2022-01-14 18:26 UTC, creator-max commented on WebAutopark.DataAccesLayer/Entities/Order.cs
> +        public DateTime Date { get; set; }
Removed this field

2022-01-14 20:00 UTC, PushMeNow requested changes

2022-01-14 20:12 UTC, creator-max commented on WebAutopark/Views/OrderElement/ConfirmDelete.cshtml
> +        <input type="hidden" asp-for="Quantity" />
fixed

2022-01-14 20:43 UTC, PushMeNow approved these changes

2022-01-15 15:53 UTC, kuzmiich commented on WebAutopark/Controllers/OrderController.cs
> +    }
Where is method Update?

2022-01-16 19:16 UTC, kuzmiich approved these changes

2022-01-31 16:14 UTC, merged